---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - breakfast.newredo.com
  resources:
  - toasts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - breakfast.newredo.com
  resources:
  - toasts/finalizers
  verbs:
  - update
- apiGroups:
  - breakfast.newredo.com
  resources:
  - toasts/status
  verbs:
  - get
  - patch
  - update
